version: "2"
linters:
  default: none
  enable:
    - gocyclo
    - bodyclose
    # - depguard
    - dogsled
    - dupl
    - errcheck
    # - funlen
    - goconst
    - gocritic
    - goprintffuncname
    - gosec
    - govet
    - ineffassign
    - lll
    - misspell
    - mnd
    - nakedret
    - prealloc
    - rowserrcheck
    - staticcheck
    - unconvert
    - unparam
    - unused
    - whitespace
    - wsl_v5
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - wsl
        text: declarations should never be cuddled
      - linters:
          - golint
        text: should not use dot imports
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
