---
name: Static tests

on:
  pull_request_target:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-static
  cancel-in-progress: true

jobs:
  unit-test:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
        id: go
      - name: Run unit tests
        run: make unit-test

  static:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
        id: go
      - name: Run static linters
        run: make static
