---
name: Int Test Linux

on: [pull_request_target]

jobs:
  int-test:
    runs-on: ubuntu-24.04
    steps:
      - name: Set up Go 1.18
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
        id: go
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: engineerd/setup-kind@v0.5.0
      - name: Run int tests
        run: sudo apt-get update && sudo apt-get install bats -y && make int-test
