---
name: Int Test MacOS

on:
  pull_request_target:
  push:
    branches:
      - main
concurrency:
  group: ${{ github.workflow }}-macos
  cancel-in-progress: true


jobs:
  int-test:
    runs-on: macos-15
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
        id: go
      - name: Install bats
        run: brew install bats
      - name: Run int tests
        run: bats tests/managers.test
